kind: pipeline
type: docker
name: random-meme-api

trigger:
  event:
    - push
    - rollback
  branch:
    - master

steps:
  - name: build
    image: maven:3.6.3-adoptopenjdk-15
    commands:
      - mvn install

  - name: copy
    image: alpine
    commands:
      - cp /drone/src/random-meme-api/target/random-meme-api-0.0.1-SNAPSHOT.jar /drone/src/
      - cp /drone/src/random-meme-api/Dockerfile /drone/src/

  - name: push
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      tags: [ "meme_api_app" ]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

